### 创建ndarray数组

In [2]:
import numpy as np

#### 基于list和tuple

In [3]:
arr_list = np.array([1, 2, 3, 4])
print(arr_list)

[1 2 3 4]


In [4]:
arr_tuple = np.array((1, 2, 3, 4))
print(arr_tuple)
arr_tuple

[1 2 3 4]


array([1, 2, 3, 4])

In [5]:
arr2 = np.array([[1, 2, 4], [3, 4, 5]])
arr2

array([[1, 2, 4],
       [3, 4, 5]])

- 一维数组用`print`输出的时候为`[1 2 3 4]`，跟python的列表是有些差异的，没有“，”
- 在创建二维数组时，在每个子list外面还有一个“[]”，形式为`[[list1], [list2]]`

#### 基于np.arange

根据start和stop指定的范围以及step设定的步长，生成一个ndarray。

`numpy.arange(start, stop, step, dtype)`

参数说明


|序号|参数|描述说明|
| --- | :---: | :--- |
| 1 | start | 起始值，默认为0
| 2 | stop | 终止值（不包含）
| 3 | step | 步长，默认为1
| 4 | dtype | 返回ndarray的数据类型，如果没有提供，则会使用输入数据的类型。 


In [6]:
arr1 = np.arange(5)
print(arr1)

[0 1 2 3 4]


In [7]:
arr2 = np.arange(0, 1, 0.1)
print(arr2)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [8]:
arr2 = np.array([np.arange(3), np.arange(3)])
print(arr2)

[[0 1 2]
 [0 1 2]]


#### 基于arange以及reshape创建多维数组

In [9]:
arr = np.arange(24).reshape(2, 3, 4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

**`arange`的长度与ndarray的维度的乘积要相等，即24 = 2X3X4**

> **练习**
>
>    创建10以内的偶数数组

> **练习**
>
> 1.创建一个一维数组
>
> 2.创建一个二维数组
>
> 3.创建嵌套序列数量不一样的数组，查看结果
>
> 4.测试数组a，将数组赋值给b，修改b中的一个元素，查看a的变化
>
> 5.紧接着4，如果想让b变化不影响a，如何实现？