# 常用函数

主要有以下方法：

| 函数名称 | 描述说明                                                     |
| :-------- | :------------------------------------------------------------ |
| resize   | 返回指定形状的新数组。                                       |
| append   | 将元素值添加到数组的末尾。                                   |
| insert   | 沿规定的轴将元素值插入到指定的元素前。                       |
| delete   | 删掉某个轴上的子数组，并返回删除后的新数组。                 |
| argwhere | 返回数组内符合条件的元素的索引值。                           |
| unique   | 用于删除数组中重复的元素，并按元素值由大到小返回一个新数组。 |
| sort()   | 对输入数组执行排序，并返回一个数组副本                       |
| argsort  | 沿着指定的轴，对输入数组的元素值进行排序，并返回排序后的元素索引数组 |

In [4]:
# 导入numpy库
import numpy as np

## numpy.resize()

`numpy.resize(arr, shape)`

numpy.resize() 返回指定形状的新数组。

numpy.resize(arr,shape) 和ndarray.resize(shape, refcheck=False)区别:
- numpy.resize(arr,shape),有返回值,返回复制内容.如果维度不够,会使用原数组数据补齐
- ndarray.resize(shape, refcheck=False),修改原数组,不会返回数据,如果维度不够,会使用0补齐

In [9]:
a = np.array([[1,2,3],[4,5,6]])
print('a数组:',a)
#a数组的形状
print('a数组形状:',a.shape)

a数组: [[1 2 3]
 [4 5 6]]
a数组形状: (2, 3)


In [10]:
b = np.resize(a, (3,3))
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [11]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a.resize((3,3), refcheck=False)
a

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

## numpy.append()

在数组的末尾添加值，默认返回一个一维数组。

`numpy.append(arr, values, axis=None)`

参数说明：

- arr：输入的数组；
- values：向 arr 数组中添加的值，需要和 arr 数组的形状保持一致；
- axis：默认为 None，返回的是一维数组；当 axis =0 时，追加的值会被添加到行，而列数保持不变，若 axis=1 则与其恰好相反。

In [14]:
a = np.array([[1,2,3],[4,5,6]])

# 向数组a添加元素
print(np.append(a, [7,8,9]))

[1 2 3 4 5 6 7 8 9]


In [15]:
# 沿轴 0 添加元素
print(np.append(a, [[7,8,9]], axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
# 沿轴 1 添加元素
print(np.append(a, [[5,5,5],[7,8,9]], axis=1))

[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


## numpy.insert()

表示沿指定的轴，在给定索引值的前一个位置插入相应的值，如果没有提供轴，则输入数组被展开为一维数组。

`numpy.insert(arr, obj, values, axis)`

参数说明：

- arr：要输入的数组
- obj：表示索引值，在该索引值之前插入 values 值；
- values：要插入的值；
- axis：指定的轴，如果未提供，则输入数组会被展开为一维数组。


In [17]:
a = np.array([[1,2],[3,4],[5,6]])

#不提供axis的情况，会将数组展开
print(np.insert(a, 3, [11,12]))

[ 1  2  3 11 12  4  5  6]


In [18]:
# 沿轴 0 垂直方向
print(np.insert(a, 1, [11], axis=0))

[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


In [19]:
# 沿轴 1 水平方向
print(np.insert(a, 1, 11, axis=1))

[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


## numpy.delete()

该方法表示从输入数组中删除指定的子数组，并返回一个新数组。它与 insert() 函数相似，若不提供 axis 参数，则输入数组被展开为一维数组。
`numpy.delete(arr, obj, axis)`

参数说明：

- arr：要输入的数组；
- obj：整数或者整数数组，表示要被删除数组元素或者子数组；
- axis：沿着哪条轴删除子数组。

In [20]:
a = np.arange(12).reshape(3,4)

# a数组
print(a)

# 不提供axis参数情况
print(np.delete(a, 5))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  6  7  8  9 10 11]


In [21]:
# 删除第二列
print(np.delete(a, 1, axis = 1))

[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


## numpy.argwhere()

该函数返回数组中非 0 元素的索引，若是多维数组则返回行、列索引组成的索引坐标。

In [22]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
y = np.argwhere(x>1)
y

array([[0, 2],
       [1, 0],
       [1, 1],
       [1, 2]])

In [24]:
y.shape

(4, 2)

## numpy.unique()

用于删除数组中重复的元素，其语法格式如下：
`numpy.unique(arr, return_index, return_inverse, return_counts)`

参数说明：

- arr：输入数组，若是多维数组则以一维数组形式展开；
- return_index：如果为 True，则返回新数组元素在原数组中的位置（索引）；
- return_inverse：如果为 True，则返回原数组元素在新数组中的位置（索引）；
- return_counts：如果为 True，则返回去重后的数组元素在原数组中出现的次数。

In [25]:
a = np.array([5,2,6,2,7,5,6,8,2,9])
print(a)

# 对a数组的去重
uq = np.unique(a)
print(uq)

[5 2 6 2 7 5 6 8 2 9]
[2 5 6 7 8 9]


In [26]:
# 数组去重后的索引数组
print("a:", a)
u, indices = np.unique(a, return_index=True)
# 打印去重后数组的索引
print(u)

print('-'*20)

print(indices)

a: [5 2 6 2 7 5 6 8 2 9]
[2 5 6 7 8 9]
--------------------
[1 0 2 4 7 9]


In [27]:
# 去重数组的下标：
ui, indices = np.unique(a, return_inverse=True)
print(ui)
print('-'*20)

# 打印下标
print(indices)

[2 5 6 7 8 9]
--------------------
[1 0 2 0 3 1 2 4 0 5]


In [28]:
# 返回去重元素的重复数量
uc, indices = np.unique(a, return_counts=True)
print(uc)

# 元素出现次数：
print(indices)

[2 5 6 7 8 9]
[3 2 2 1 1 1]


## numpy.sort()

对输入数组执行排序，并返回一个数组副本。
`numpy.sort(a, axis, kind, order)`

参数说明：

- a：要排序的数组；
- axis：沿着指定轴进行排序，如果没有指定 axis，默认在最后一个轴上排序，若 axis=0 表示按列排序，axis=1 表示按行排序；
- kind：默认为 quicksort（快速排序）；
- order：若数组设置了字段，则 order 表示要排序的字段。

In [31]:
a = np.array([[3,7,5],[6,1,4]]) 
print('a数组是：', a)

#调用sort()函数
print('排序后的内容:', np.sort(a))

a数组是： [[3 7 5]
 [6 1 4]]
排序后的内容: [[3 5 7]
 [1 4 6]]


In [32]:
# 以行为参照,列上面的数据排序：
print(np.sort(a, axis=0))

[[3 1 4]
 [6 7 5]]


In [33]:
# 列为参照,行上面的数据排序：
print(np.sort(a, axis=1))

[[3 5 7]
 [1 4 6]]


In [34]:
np.array([("raju",21),("anil",25),("ravi",  17),  ("amar",27)])

array([['raju', '21'],
       ['anil', '25'],
       ['ravi', '17'],
       ['amar', '27']], dtype='<U4')

In [35]:
# 设置在sort函数中排序字段
dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.7, 38)]
a = np.array(values, dtype=dtype)
a

array([(b'Arthur', 1.8, 41), (b'Lancelot', 1.9, 38),
       (b'Galahad', 1.7, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [36]:
np.sort(a, order='height') 

array([(b'Galahad', 1.7, 38), (b'Arthur', 1.8, 41),
       (b'Lancelot', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [41]:
np.sort(a, order=['age', 'height'])

array([(b'Galahad', 1.7, 38), (b'Lancelot', 1.9, 38),
       (b'Arthur', 1.8, 41)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

# 操作文件  loadtxt

loadtxt读取txt文本、csv文件

`loadtxt(fname, dtype=<type 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0,encoding='bytes')`

参数：

- fname：指定文件名称或字符串。支持压缩文件，包括gz、bz格式。

- dtype：数据类型。 默认float。

- comments：字符串或字符串组成的列表。表示注释字符集开始的标志，默认为#。

- delimiter：字符串。分隔符。

- converters：字典。将特定列的数据转换为字典中对应的函数的浮点型数据。例如将空值转换为0，默认为空。

- skiprows：跳过特定行数据。例如跳过前1行（可能是标题或注释）。默认为0。

- usecols：元组。用来指定要读取数据的列，第一列为0。例如（1， 3， 5），默认为空。

- unpack：布尔型。指定是否转置数组，如果为真则转置，默认为False。

- ndmin：整数型。指定返回的数组至少包含特定维度的数组。值域为0、1、2，默认为0。
- encoding:编码,  确认文件是gbk还是utf-8 格式

返回：从文件中读取的数组。

## 文件读取

In [52]:
data = np.loadtxt('./student-data.txt', dtype=object, skiprows=9)

In [53]:
data

array([['JW-1', 'M', '19/12/95', '1.82', '92.4', '119/76', '39.3'],
       ['JW-2', 'M', '11/1/96', '1.77', '80.9', '114/73', '35.5'],
       ['JW-3', 'F', '2/10/95', '1.68', '69.7', '124/79', '29.1'],
       ['JW-6', 'M', '6/7/95', '1.72', '75.5', '110/60', '45.5'],
       ['JW-7', 'F', '28/3/96', '1.66', '72.4', '101/68', '-'],
       ['JW-9', 'F', '11/12/95', '1.78', '82.1', '115/75', '32.3'],
       ['JW-10', 'F', '7/4/96', '1.60', '-', '-/-', '30.1'],
       ['JW-11', 'M', '22/8/95', '1.72', '77.2', '97/63', '48.8'],
       ['JW-12', 'M', '23/5/96', '1.83', '88.9', '105/70', '37.7'],
       ['JW-14', 'F', '12/1/96', '1.56', '56.3', '108/72', '26.0'],
       ['JW-15', 'F', '1/6/96', '1.64', '65.0', '99/67', '35.7'],
       ['JW-16', 'M', '10/9/95', '1.63', '73.0', '131/84', '29.9'],
       ['JW-17', 'M', '17/2/96', '1.67', '89.8', '101/76', '40.2'],
       ['JW-18', 'M', '31/7/96', '1.66', '75.1', '-/-', '-'],
       ['JW-19', 'F', '30/10/95', '1.59', '67.3', '103/69', '33.5'],
   

In [54]:
# 读取csv文件，要设置分隔符，csv默认是逗号

data = np.loadtxt('./csv_test.csv', dtype=np.int32, delimiter=',')

In [55]:
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]], dtype=int32)